    <main id="body">
        <div id="header"></div>
        <div id="main">
            <h1>Teste de imagem de fundo</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt perferendis fugit dolore ut necessitatibus molestiae consectetur odio optio nostrum quae excepturi nulla suscipit aut, consequatur libero assumenda id? Alias, eveniet. Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi sed iste dicta harum maiores laudantium dolore accusantium magni cupiditate, sunt quia? Officia minima est, iusto corporis asperiores repellat quidem explicabo! Lorem ipsum dolor sit amet consectetur adipisicing elit. Et natus impedit quo earum, reiciendis in laudantium quis tempore recusandae, illo corrupti eaque quaerat libero ipsa nobis cum, fugiat est voluptates.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt perferendis fugit dolore ut necessitatibus molestiae consectetur odio optio nostrum quae excepturi nulla suscipit aut, consequatur libero assumenda id? Alias, eveniet. Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi sed iste dicta harum maiores laudantium dolore accusantium magni cupiditate, sunt quia? Officia minima est, iusto corporis asperiores repellat quidem explicabo! Lorem ipsum dolor sit amet consectetur adipisicing elit. Et natus impedit quo earum, reiciendis in laudantium quis tempore recusandae, illo corrupti eaque quaerat libero ipsa nobis cum, fugiat est voluptates.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt perferendis fugit dolore ut necessitatibus molestiae consectetur odio optio nostrum quae excepturi nulla suscipit aut, consequatur libero assumenda id? Alias, eveniet. Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi sed iste dicta harum maiores laudantium dolore accusantium magni cupiditate, sunt quia? Officia minima est, iusto corporis asperiores repellat quidem explicabo! Lorem ipsum dolor sit amet consectetur adipisicing elit. Et natus impedit quo earum, reiciendis in laudantium quis tempore recusandae, illo corrupti eaque quaerat libero ipsa nobis cum, fugiat est voluptates.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt perferendis fugit dolore ut necessitatibus molestiae consectetur odio optio nostrum quae excepturi nulla suscipit aut, consequatur libero assumenda id? Alias, eveniet. Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi sed iste dicta harum maiores laudantium dolore accusantium magni cupiditate, sunt quia? Officia minima est, iusto corporis asperiores repellat quidem explicabo! Lorem ipsum dolor sit amet consectetur adipisicing elit. Et natus impedit quo earum, reiciendis in laudantium quis tempore recusandae, illo corrupti eaque quaerat libero ipsa nobis cum, fugiat est voluptates.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt perferendis fugit dolore ut necessitatibus molestiae consectetur odio optio nostrum quae excepturi nulla suscipit aut, consequatur libero assumenda id? Alias, eveniet. Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi sed iste dicta harum maiores laudantium dolore accusantium magni cupiditate, sunt quia? Officia minima est, iusto corporis asperiores repellat quidem explicabo! Lorem ipsum dolor sit amet consectetur adipisicing elit. Et natus impedit quo earum, reiciendis in laudantium quis tempore recusandae, illo corrupti eaque quaerat libero ipsa nobis cum, fugiat est voluptates.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt perferendis fugit dolore ut necessitatibus molestiae consectetur odio optio nostrum quae excepturi nulla suscipit aut, consequatur libero assumenda id? Alias, eveniet. Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi sed iste dicta harum maiores laudantium dolore accusantium magni cupiditate, sunt quia? Officia minima est, iusto corporis asperiores repellat quidem explicabo! Lorem ipsum dolor sit amet consectetur adipisicing elit. Et natus impedit quo earum, reiciendis in laudantium quis tempore recusandae, illo corrupti eaque quaerat libero ipsa nobis cum, fugiat est voluptates.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt perferendis fugit dolore ut necessitatibus molestiae consectetur odio optio nostrum quae excepturi nulla suscipit aut, consequatur libero assumenda id? Alias, eveniet. Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi sed iste dicta harum maiores laudantium dolore accusantium magni cupiditate, sunt quia? Officia minima est, iusto corporis asperiores repellat quidem explicabo! Lorem ipsum dolor sit amet consectetur adipisicing elit. Et natus impedit quo earum, reiciendis in laudantium quis tempore recusandae, illo corrupti eaque quaerat libero ipsa nobis cum, fugiat est voluptates.</p>
        </div>
        <div id="footer"></div>
    </main>